### PR TITLE
Timestamped stream

### PR DESCRIPTION
**Pull request by Gold872**
Hopefully did the merging correctly this time

### CODE REVIEW

**Comment by Gold872** [comment]
Using a record was a good call, it's much cleaner. I had no idea they even existed

**Comment by mjansen4857** [comment]
Can you have it return a DateTime instead of int? Then this is good to merge.

**Comment by Gold872** [comment]
Yes, I also forgot to add a way of getting the network latency, so I'll add that and then that should be all I have to add until I figure out how structs work

**Comment by mjansen4857** [comment]
Just an FYI there was a little oopsie that would keep closing the connection because it was comparing the last received timestamp (in microseconds) to the timeout interval in milliseconds. I fixed it [here](https://github.com/mjansen4857/nt4/pull/7). Just be aware if that exists in your implementation or you use v1.3 that will be a bit broken. Pushing 1.3.1 rn so that should get pulled if you try to use 1.3 anyways

**Comment by mjansen4857** [comment]
@Gold872  Another random weird problem you should be aware of for your elastic implementation:

It seems like due to the magic of relying on third party libraries, the messagepack unpacker that is unpacking the messages from the rtt websocket will decide that the topic ID should be unpacked as an **unsigned** int instead of a signed int. This would cause the client to believe that the connection timed out because it would be receiving timestamps for the topic ID 255 instead of -1. I'm fixing this by just ignoring the topic ID for the rtt websocket, since it should only send timestamps anyways. Correct me if I'm wrong on that.

EDIT: It is also completely possible this is a WPILib issue, and it is actually sending topic ID 255. I might try looking into that.
EDIT 2: I believe I've confirmed that its not a WPILib issue. The byte indicating topic ID does not change in value, the unpacker just does it wrong for whatever reason. The messagepack package hasn't been updated in 2 years. So probably no hope of that getting fixed. I'll see if I can get it working with something else at some point.

**Comment by Gold872** [comment]
> Just an FYI there was a little oopsie that would keep closing the connection because it was comparing the last received timestamp (in microseconds) to the timeout interval in milliseconds. I fixed it [here](https://github.com/mjansen4857/nt4/pull/7). Just be aware if that exists in your implementation or you use v1.3 that will be a bit broken. Pushing 1.3.1 rn so that should get pulled if you try to use 1.3 anyways

Not sure how I didn't notice that, with elastic I convert it to milliseconds so I probably just forgot to copy that part over

> It seems like due to the magic of relying on third party libraries, the messagepack unpacker that is unpacking the messages from the rtt websocket will decide that the topic ID should be unpacked as an **unsigned** int instead of a signed int. This would cause the client to believe that the connection timed out because it would be receiving timestamps for the topic ID 255 instead of -1. I'm fixing this by just ignoring the topic ID for the rtt websocket, since it should only send timestamps anyways. Correct me if I'm wrong on that.

That's odd, I haven't seen that happen but I'll experiment around with it. Ignoring the topic ID though is a good fix since no other info gets sent over RTT

**Comment by mjansen4857** [comment]
I got it working with messagepack_dart over messagepack and it doesn't seem to have this issue. But, it will not handle multiple messages in the same messagepack message properly which is why I didn't use it in the first place. I guess I'll have to use one for RTT and the other for the main websocket lol. This sucks

**Comment by Gold872** [comment]
This is really interesting, since for me the topic IDs are all signed, so I'm not having any weird disconnect issues. What OS and WPILib versions are you running?

**Comment by mjansen4857** [comment]
Windows, happens on both beta 3 and 4. It can take a while sometimes. Seems to happen faster when there is some data flowing through the client.

I've definitely isolated it to being an issue with the messagepack package, so its nothing to do with WPILib/nt itself. I've already merged a fix that just uses a different package for RTT so we're good there.

**Comment by Gold872** [comment]
I (finally) started to have this issue with elastic, and what I've done is instead of using a different package just for the RTT (which technically the issue could still happen if it's not using the RTT protocol), is I check the bitwise complement of the topic ID and 0xFF (so it ignores the signature)
```dart
if (topicID & 0xFF == 0xFF) {
    _rttHandleReceiveTimestamp(...);
}
```
So far its been working pretty well

Not sure if I've mentioned this but elastic is using a modified version of this package since I had to optimize it for things like subscription counting/sharing. I don't want to include these features in the package since then it will require everyone to not copy subscriptions with `=`, and dart doesn't have features like C++ where you can override copy constructors and destructors, so all of the instance counting has to be done manually.

**Pull request merged**
